server:
  port: 9090
spring:
  profiles:
    active: dev

---
#dev environment
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lol_loupe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: i18n/messages #相对路径 开头请勿添加斜杠

mybatis:
  config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.domain

---
#prod
